image: ghcr.io/cirruslabs/flutter:3.19.6

stages:
  - build

before_script:
  - flutter doctor -v
  - flutter pub get

build_apk:
  stage: build
  script:
    - flutter build apk --release --no-tree-shake-icons
  artifacts:
    name: "smart-driver-2-apk"
    paths:
      - build/app/outputs/flutter-apk/app-release.apk
    expire_in: 30 days
  timeout: 45m
