version: 1.0.{build}
image: Ubuntu2004
environment:
  FLUTTER_VERSION: 3.16.0
install:
  - git clone https://github.com/flutter/flutter.git -b stable --depth 1
  - export PATH="$PATH:`pwd`/flutter/bin"
  - flutter doctor
build_script:
  - flutter pub get
  - flutter build apk --release
artifacts:
  - path: build/app/outputs/flutter-apk/app-release.apk
    name: smart-driver-2.apk
