FROM cirrusci/flutter:3.16.0

# Установка зависимостей
RUN apt-get update && apt-get install -y \
    git \
    wget \
    curl \
    unzip \
    && rm -rf /var/lib/apt/lists/*

# Рабочая директория
WORKDIR /app

# Копируем проект
COPY . .

# Устанавливаем зависимости
RUN flutter pub get

# Собираем APK
RUN flutter build apk --release

# Копируем APK в вывод
CMD ["cp", "build/app/outputs/flutter-apk/app-release.apk", "/output/smart-driver-2.apk"]
