FROM ghcr.io/cirruslabs/flutter:stable

# Установка зависимостей
RUN apt-get update && apt-get install -y \
    git \
    wget \
    curl \
    unzip \
    && rm -rf /var/lib/apt/lists/*

# Рабочая директория
WORKDIR /app

# Копируем проект
COPY . .

# Устанавливаем зависимости
RUN flutter pub get

# Собираем APK
RUN flutter build apk --release

# Выводим результат
RUN ls -lh build/app/outputs/flutter-apk/
